# Starship Configuration
# Cross-shell prompt for astronauts

format = """
[╭─](bold blue)$username$hostname$directory$git_branch$git_status$python$nodejs$rust$java$golang$cmd_duration
[╰─](bold blue)$character"""

right_format = """$time"""

[username]
style_user = "bold green"
style_root = "bold red"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "on [$hostname](bold purple) "
disabled = false

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = false
format = "in [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
style = "bold yellow"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
format = '([\[$all_status$ahead_behind\]]($style) )'

[python]
symbol = " "
style = "bold green"
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
symbol = " "
style = "bold green"
format = 'via [$symbol($version )]($style)'

[rust]
symbol = " "
style = "bold red"
format = 'via [$symbol($version )]($style)'

[java]
symbol = " "
style = "bold orange"
format = 'via [$symbol($version )]($style)'

[golang]
symbol = " "
style = "bold cyan"
format = 'via [$symbol($version )]($style)'

[cmd_duration]
min_time = 2_000
style = "bold yellow"
format = "took [$duration]($style) "

[time]
disabled = false
format = '🕙 [$time]($style) '
time_format = "%T"
style = "bold white"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vicmd_symbol = "[❮](bold green)"

[package]
disabled = true